### ISSUE TITLE
Mudança de nome do repositório

### ISSUE THREAD

**Issue by gjuniioor** [bahiajs/bahiajs.github.io#1]
Opa, recomendo que mudem o nome do repositório para já usar o github pages. Renomeia para bahiajs.github.io que ele vai ficar online justamente nesse [link](https://bahiajs.github.io).

Depois, se quiser utilizar o domínio bahiajs.org, basta adicionar uma entrada CNAME nos registros de DNS do domínio para o github e adicionar um arquivo `CNAME` com o domínio aqui no repositório.

O bom que como o github pages provê páginas estáticas, fazer algo com JS fica bacana por aqui.

**Comment by mvfsilva** [comment]
Obrigado @gjuniioor
